# Generated by Django 2.2.5 on 2024-08-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0003_auto_20240829_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarecord',
            old_name='children_people',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='datarecord',
            old_name='day',
            new_name='other_stuff',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='amount_cost',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='eight_scripts',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='eleven_scripts',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='lunch_item',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='lunch_sale',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='money_collected',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='nine_lunch_sale',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='nine_scripts',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='non_seniors',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='person_free_bday',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='script_money_collected',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='script_sale',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='senior_people',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='six_scripts',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='total_paying_people',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='total_people',
        ),
        migrations.RemoveField(
            model_name='datarecord',
            name='volunteer_people',
        ),
    ]
