# Generated by Django 2.2.5 on 2024-08-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0004_auto_20240830_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='date',
            field=models.DateTimeField()
            #field=models.IntegerField(blank=True, null=True),
        ),
    ]
