# Generated by Django 2.2.5 on 2024-08-31 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddata', '0005_auto_20240830_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datarecord',
            old_name='data',
            new_name='children_people',
        ),
        migrations.RenameField(
            model_name='datarecord',
            old_name='other_stuff',
            new_name='day',
        ),
        migrations.AddField(
            model_name='datarecord',
            name='amount_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='diff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='eight_scripts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='eleven_scripts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='lunch_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='lunch_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='money_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='nine_lunch_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='nine_scripts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='non_seniors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='person_free_bday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='script_money_collected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='script_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='senior_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='six_scripts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='total_paying_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='total_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='volunteer_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
